Repository qri-io/desktop, pull requests merged in 2019-09, with the labels that each got.

#151 fix(cloud link): show in cloud should use QRI_CLOUD_URL
  app/components/Dataset.tsx
  app/utils/registry.ts
Labels: fix

#153 Various Improvements
  app/assets/ss-pika.eot
  app/assets/ss-pika.svg
  app/assets/ss-pika.ttf
  app/assets/ss-pika.woff
  app/assets/style.css
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetComponent.tsx
  app/components/HandsonTable.tsx
  app/components/SaveForm.tsx
  app/components/Toast.tsx
  app/components/WelcomeTemplate.tsx
  app/components/chrome/HeaderColumnButton.tsx
  app/components/chrome/HeaderColumnButtonDropdown.tsx
  app/scss/_dataset.scss
  app/scss/_form.scss
  app/scss/_saveform.scss
  app/scss/_type.scss
  package.json
  yarn.lock
Labels: fix

#154 fix(windows): Fix Windows crashes at startup. Improve installer.
  app/main.development.js
  package.json
Labels: bug, build, main process

#157 feat: Command-R Shortcut
  app/components/Dataset.tsx
  app/main.development.js
Labels: feat

#156 feat(auto update): use electron-updater for auto updates
  app/main.development.js
  package.json
  resources/icon.icns
  resources/icon.ico
  resources/icon.png
  resources/icons/1024x1024.png
  resources/icons/128x128.png
  resources/icons/16x16.png
  resources/icons/24x24.png
  resources/icons/256x256.png
  resources/icons/32x32.png
  resources/icons/48x48.png
  resources/icons/512x512.png
  resources/icons/64x64.png
  resources/icons/96x96.png
  yarn.lock
Labels: feat, main process

#159 docs(readmes): add code of conduct, contributer, developer, changelog and small makefile
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTOR.md
  DEVELOPER.md
  Makefile
  README.md
Labels: docs

#160 feat: show window on refocusing app
  app/main.development.js
Labels: feat, main process

#161 chore(release candidate): version v0.1.0-rc1
  CHANGELOG.md
  Makefile
  app/main.development.js
  app/package.json
  package.json
  version.js
Labels: chore

#162 fix: close the dataset list when a new dataset is loaded
  app/reducers/ui.ts
Labels: fix

#163 New dataset modal
  app/actions/api.ts
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/form/TextInput.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/Header.tsx
  app/scss/_dataset-list.scss
  app/scss/_dataset.scss
  app/scss/_dialog.scss
  app/scss/style.scss
Labels: refactor, ui

#181 fix(DatasetList): fix filter
  app/actions/api.ts
  app/components/DatasetList.tsx
Labels: bug

#182 fix(*): various bugs from tutorial walkthrough
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/DatasetSidebar.tsx
  app/components/ParseError.tsx
  app/containers/DatasetListContainer.tsx
  app/main.development.js
Labels: fix

#183 fix(selection): when we signin/signup, clear the selection
  app/actions/selections.ts
  app/components/Signin.tsx
  app/components/Signup.tsx
  app/components/form/DebouncedTextInput.tsx
  app/components/form/TextInput.tsx
  app/containers/RoutesContainer.tsx
  app/reducers/selections.ts
  app/routes.tsx
Labels: fix

#203 Various fixes and refactoring
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/form/TextInput.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/Modal.tsx
  app/main.development.js
  app/reducers/selections.ts
  app/scss/_dataset.scss
  app/scss/_forms.scss
  app/scss/_welcome.scss
  app/utils/formValidation.ts
  test/app/utils/formValidation.test.ts
  test/runTests.js
  yarn.lock
Labels: fix

#207 fix(api, init, add, profile menu): More fixes and refactoring
  app/actions/api.ts
  app/components/App.tsx
  app/components/Dataset.tsx
  app/components/DatasetComponent.tsx
  app/components/chrome/HeaderColumnButtonDropdown.tsx
  app/components/modals/AddDataset.tsx
  app/components/modals/CreateDataset.tsx
  app/reducers/workingDataset.ts
  app/store/api.ts
  app/store/mapError.ts
Labels: fix, refactor

#211 fix(windows): Fix some things for Windows and production build
  app/main.development.js
  webpack.config.production.js
Labels: fix

#210 feat: validate commit form
  app/actions/mutations.ts
  app/actions/ui.ts
  app/components/Dataset.tsx
  app/components/DatasetSidebar.tsx
  app/components/SaveForm.tsx
  app/containers/DatasetContainer.tsx
  app/containers/DatasetSidebarContainer.tsx
  app/containers/SaveFormContainer.tsx
  app/models/store.ts
  app/reducers/mutations.ts
  app/reducers/ui.ts
  app/scss/_dataset.scss
  app/scss/_saveform.scss
  app/scss/_site.scss
  app/utils/formValidation.ts
  test/app/utils/formValidation.test.ts
Labels: feat

#215 Dataset list items
  app/actions/api.ts
  app/components/DatasetList.tsx
  app/scss/_dataset-list.scss
  package.json
Labels: feat

#213 refactor(selections): all actions that should effect selection are caught in the reducer
  app/actions/api.ts
  app/components/CommitDetails.tsx
  app/components/Dataset.tsx
  app/components/NoDatasetSelected.tsx
  app/containers/CommitDetailsContainer.tsx
  app/containers/RoutesContainer.tsx
  app/reducers/selections.ts
  app/routes.tsx
  app/utils/chooseDefaultComponent.ts
  package.json
  test/app/reducers/selections.test.ts
  test/app/utils/chooseDefaultComponent.test.ts
  yarn.lock
Labels: fix, refactor

#221 fix: handle windows paths
  app/components/ComponentList.tsx
  app/components/modals/CreateDataset.tsx
Labels: fix

#225 Refactor(*): stabilizing app
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/components/App.tsx
  app/components/Body.tsx
  app/components/CommitDetails.tsx
  app/reducers/commitDetail.ts
  app/reducers/myDatasets.ts
  app/reducers/selections.ts
  app/reducers/workingDataset.ts
  test/e2e/e2e.spec.ts
Labels: refactor

#226 feat: dataset removal
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/components/App.tsx
  app/components/DatasetList.tsx
  app/components/form/CheckboxInput.tsx
  app/components/modals/RemoveDataset.tsx
  app/containers/AppContainer.tsx
  app/models/modals.ts
  app/models/store.ts
  app/scss/_dataset.scss
  app/scss/_dialog.scss
  app/scss/_modal.scss
  app/scss/_site.scss
  app/scss/_welcome.scss
Labels: feat

#227 feat: publish and unpublish modals
  app/actions/api.ts
  app/components/App.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/chrome/HeaderColumnButtonDropdown.tsx
  app/components/modals/PublishDataset.tsx
  app/components/modals/UnpublishDataset.tsx
  app/containers/AppContainer.tsx
  app/main.development.js
  app/models/modals.ts
  app/scss/_dataset-list.scss
  app/scss/_dataset.scss
  app/scss/_dialog.scss
Labels: chore, feat, fix, refactor, ui

#233 test(circleci): add circleci config
  .circleci/config.yml
  app/utils/localStore.ts
  codecov.yml
  package.json
  yarn.lock
Labels: feat

#234 fix(NoDatasets, SaveForm): refactor our 'no datasets' story, fix commit bug
  app/actions/mutations.ts
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/DatasetSidebar.tsx
  app/components/NoDatasets.tsx
  app/components/SaveForm.tsx
  app/components/WelcomeTemplate.tsx
  app/containers/DatasetContainer.tsx
  app/containers/SaveFormContainer.tsx
  app/reducers/mutations.ts
  app/routes.tsx
  app/scss/_dataset.scss
  app/scss/_welcome.scss
Labels: UX, fix

#244 fix: commit highlighting
  app/components/DatasetSidebar.tsx
Labels: fix

#241 refactor: tooltip audit
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/DatasetSidebar.tsx
  app/components/modals/CreateDataset.tsx
Labels: refactor

#238 fix(*): fetchWorkingDataset, CommitDetails & WorkingDataset handling body, failed to fetch errors
  app/actions/api.ts
  app/actions/ui.ts
  app/components/App.tsx
  app/components/Body.tsx
  app/components/Dataset.tsx
  app/components/DatasetSidebar.tsx
  app/components/Signin.tsx
  app/components/Signup.tsx
  app/components/chrome/Spinner.tsx
  app/components/chrome/Toast.tsx
  app/containers/AppContainer.tsx
  app/containers/SaveFormContainer.tsx
  app/models/store.ts
  app/reducers/commitDetail.ts
  app/reducers/connection.ts
  app/reducers/index.ts
  app/reducers/mutations.ts
  app/reducers/myDatasets.ts
  app/reducers/page.ts
  app/reducers/selections.ts
  app/reducers/ui.ts
  app/reducers/workingDataset.ts
  app/scss/_dataset.scss
  app/store/api.ts
  app/utils/actionType.ts
  app/utils/bodyValue.ts
  test/app/reducers/connection.test.ts
  test/app/utils/actionTypes.test.ts
Labels: fix

#255 fix(delete, pagination): clean up state tree on delete, fix pagination issues
  app/actions/api.ts
  app/containers/AppContainer.tsx
  app/reducers/commitDetail.ts
  app/reducers/myDatasets.ts
  app/reducers/page.ts
  app/reducers/selections.ts
  app/reducers/workingDataset.ts
  app/store/api.ts
  app/utils/pagination.ts
  test/app/reducers/selections.test.ts
  test/app/utils/pagination.test.ts
  yarn.lock
Labels: fix

#254 feat(backend): log backend output to tmp/io.qri.desktop/qri.log
  app/backend.js
Labels: backend, feat

#267 fix(bootstrap, backend version, defaultPollInterval, pageInfo): lots of fixes
  app/actions/session.ts
  app/components/App.tsx
  app/components/Body.tsx
  app/components/Dataset.tsx
  app/containers/AppContainer.tsx
  app/main.development.js
  app/package.json
  app/reducers/ui.ts
  app/store/api.ts
Labels: fix

#270 refactor(reset components): simplify process
  app/actions/workingDataset.ts
  app/components/App.tsx
  app/components/Dataset.tsx
  app/containers/DatasetContainer.tsx
  app/reducers/workingDataset.ts
Labels: fix, refactor

#280 fix(*): Lots o fixes
  app/actions/api.ts
  app/actions/selections.ts
  app/actions/ui.ts
  app/components/App.tsx
  app/components/Body.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/modals/AddDataset.tsx
  app/components/modals/CreateDataset.tsx
  app/containers/AppContainer.tsx
  app/containers/MetadataEditorContainer.tsx
  app/containers/SaveFormContainer.tsx
  app/models/session.ts
  app/models/store.ts
  app/reducers/index.ts
  app/reducers/selections.ts
  app/reducers/ui.ts
  app/reducers/workingDataset.ts
  app/scss/_dataset.scss
  app/store/api.ts
  test/app/reducers/selections.test.ts
Labels: fix

#285 fix:restore body pagination
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/reducers/workingDataset.ts
Labels: fix

#286 26 sep improvements
  app/actions/api.ts
  app/components/CommitDetails.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/DatasetSidebar.tsx
  app/components/MetadataEditor.tsx
  app/components/NoDatasets.tsx
  app/components/chrome/HeaderColumnButton.tsx
  app/components/form/CheckboxInput.tsx
  app/components/form/DropdownInput.tsx
  app/components/form/InputLabel.tsx
  app/components/form/MultiStructuredInput.tsx
  app/components/form/MultiTextInput.tsx
  app/components/form/TextAreaInput.tsx
  app/components/form/TextInput.tsx
  app/components/modals/AddDataset.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/Modal.tsx
  app/components/modals/PublishDataset.tsx
  app/reducers/ui.ts
  app/scss/_dataset.scss
  app/scss/_dialog.scss
  app/scss/_forms.scss
  app/scss/_site.scss
  app/scss/_toast.scss
  app/scss/_type.scss
  app/scss/_variables.scss
  app/scss/_welcome.scss
  app/utils/formValidation.ts
  package.json
  yarn.lock
Labels: feat, fix, refactor, ui

#287 chore(release): release v0.1.0
  CHANGELOG.md
  app/main.development.js
  app/package.json
  package.json
Labels: chore
