Repository qri-io/desktop, pull requests merged in 2019-11, with the labels that each got.

#317 chore(*): add build steps to notarize app
  app/components/form/InputLabel.tsx
  app/components/form/MultiStructuredInputRow.tsx
  app/index.tsx
  entitlements.mac.inherit.plist
  notarize.js
  package.json
  webpack.config.development.js
  yarn.lock
Labels: chore

#318 chore(release): release v0.2.0
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore

#319 feat(drag-and-drop): drag and drop a data file to create a dataset
  app/components/App.tsx
  app/components/BodyTable.tsx
  app/components/modals/CreateDataset.tsx
  app/containers/AppContainer.tsx
  app/reducers/ui.ts
  app/scss/_drag-drop.scss
  app/scss/_welcome.scss
  app/scss/style.scss
Labels: feat

#314 feat: add readme component
  app/actions/api.ts
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetComponent.tsx
  app/components/ReadMe.tsx
  app/components/ReadmeHistory.tsx
  app/containers/ReadmeContainer.tsx
  app/containers/ReadmeHistoryContainer.tsx
  app/models/store.ts
  app/reducers/commitDetail.ts
  app/reducers/workingDataset.ts
  app/scss/_readme.scss
  app/scss/_site.scss
  app/scss/style.scss
  package.json
  version.js
  yarn.lock
Labels: feat

#323 refactor(removeDataset): adjust action to work with new api flags
  app/actions/api.ts
Labels: refactor

#324 feat(detailsBar): let's add a details bar on the dataset body page
  app/actions/api.ts
  app/actions/ui.ts
  app/components/Body.tsx
  app/components/BodyTable.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DetailsBar.tsx
  app/containers/BodyContainer.tsx
  app/containers/DatasetContainer.tsx
  app/containers/DetailsBarContainer.tsx
  app/models/details.ts
  app/models/store.ts
  app/reducers/commitDetail.ts
  app/reducers/ui.ts
  app/reducers/workingDataset.ts
  app/scss/_dataset.scss
Labels: feat, ui

#325 feat(storybook,Stat): initial string Stat component with story
  .babelrc
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  app/components/stats/Stat.tsx
  app/scss/_stats.scss
  app/scss/style.scss
  package.json
  stories/0-Stats.stories.tsx
  stories/data/stats_nyc_report_family_justice_center_stats.json
  yarn.lock
Labels: feat, ui

#326 feat(Boolean Stat Chart): add boolean stat, move Stat component
  app/components/StatsChart.tsx
  package.json
  stories/0-Stats.stories.tsx
  stories/data/stats_all_types.json
  yarn.lock
Labels: feat, ui

#328 feat(DetailsBar): add stats component to details bar
  app/components/DetailsBar.tsx
Labels: feat, ui

#329 fix(StatsChart): fix rename bugs
  app/components/DetailsBar.tsx
  app/components/StatsChart.tsx
Labels: fix

#332 refactor(DetailsBar): add stat type
  app/components/DetailsBar.tsx
  app/scss/_dataset.scss
Labels: refactor

#330 feat(transform): initial support for transform display
  app/components/Code.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetComponent.tsx
  app/components/Transform.tsx
  app/containers/TransformContainer.tsx
  app/models/store.ts
  app/reducers/workingDataset.ts
  stories/1-CodeViewer.stories.tsx
Labels: feat, ui

#333 fix(bodyValue): account for null or undefined previous body values
  app/components/ComponentList.tsx
  app/utils/bodyValue.ts
  test/app/utils/bodyValue.test.ts
Labels: fix

#340 chore(release): release v0.2.1
  CHANGELOG.md
  app/package.json
  package.json
  test/e2e/e2e.spec.ts
  version.js
Labels: chore

#344 docs(release): adds steps on how to put out a release
  DEVELOPER.md
  RELEASE_PROCESS.md
Labels: docs
