Repository qri-io/desktop, pull requests merged in 2020-03, with the labels that each got.

#465 feat(ErrorHandler): handle react errors, crash reports
  app/components/ErrorHandler.tsx
  app/constants.js
  app/index.tsx
  app/scss/0.4.0/errorHandler.scss
  app/scss/style.scss
Labels: feat

#468 fix(workbench, network): clean up!
  app/actions/api.ts
  app/assets/lost_blob.png
  app/components/dataset/Preview.tsx
  app/components/dataset/PreviewNotFound.tsx
  app/components/item/HistoryListItem.tsx
  app/components/network/LogList.tsx
  app/components/workbench/NotInNamespace.tsx
  app/components/workbench/UnlinkedDataset.tsx
  app/components/workbench/Workbench.tsx
  app/components/workbench/WorkbenchSidebar.tsx
  app/containers/WorkbenchContainer.tsx
  app/scss/0.4.0/preview.scss
  app/scss/_dataset.scss
  app/scss/style.scss
  test/e2e/e2e.spec.ts
Labels: fix

#469 fix(workbench): viewing transform component shouldn't crash
  app/components/Code.tsx
  app/components/DetailsBar.tsx
  app/components/HistoryCommit.tsx
  app/components/Navbar.tsx
  app/components/ReadmeHistory.tsx
  app/components/Transform.tsx
  app/components/dataset/ReadmeSegment.tsx
  app/components/workbench/Body.tsx
  app/components/workbench/Commit.tsx
  app/components/workbench/CommitDetails.tsx
  app/components/workbench/CommitDetailsHeader.tsx
  app/components/workbench/CommitHistory.tsx
  app/components/workbench/DatasetComponent.tsx
  app/components/workbench/Metadata.tsx
  app/components/workbench/MetadataEditor.tsx
  app/components/workbench/ParseError.tsx
  app/components/workbench/ReadmeHistory.tsx
  app/components/workbench/Transform.tsx
  app/components/workbench/Workbench.tsx
  app/containers/CommitContainer.tsx
  app/containers/CommitHistoryContainer.tsx
  app/containers/MetadataContainer.tsx
  app/containers/MetadataEditorContainer.tsx
  app/containers/ReadmeHistoryContainer.tsx
  app/containers/TransformContainer.tsx
  app/containers/WorkbenchContainer.tsx
  app/models/dataset.ts
  app/reducers/commitDetail.ts
  app/reducers/workingDataset.ts
  app/routes.tsx
  webpack.config.development.js
  webpack.config.production.js
Labels: chore, fix, refactor

#470 feat(compare): compare two csv files with compare section
  app/components/Navbar.tsx
  app/components/chrome/Icon.tsx
  app/components/compare/Compare.tsx
  app/components/compare/CompareMain.tsx
  app/components/compare/CompareSidebar.tsx
  app/components/compare/DiffStat.tsx
  app/components/compare/LineDiff.tsx
  app/components/compare/TableDiff.tsx
  app/components/compare/TableDiffSchemaHead.tsx
  app/components/form/ButtonInput.tsx
  app/routes.tsx
  app/scss/0.4.0/compare.scss
  app/scss/0.4.0/icons.scss
  app/scss/_sidebar-layout.scss
  app/scss/_tableDiff.scss
  app/scss/style.scss
  webpack.config.development.js
  webpack.config.production.js
Labels: feat

#473 fix(*) punchlist
  app/components/StatsChart.tsx
  app/components/chrome/Icon.tsx
  app/components/workbench/Body.tsx
  app/components/workbench/MetadataEditor.tsx
Labels: api

#472 feat(history): show hash in CommitDetailsHeader
  app/components/Layout.tsx
  app/components/workbench/CommitDetails.tsx
  app/components/workbench/CommitDetailsHeader.tsx
  app/scss/_dataset.scss
Labels: feat, workbench

#474 style(compare): fix scrolling and height
  app/components/workbench/NotInNamespace.tsx
  app/scss/0.4.0/compare.scss
  app/scss/_tableDiff.scss
Labels: fix

#475 chore(release): version 0.4.0
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore

#499 feat(selections): adding workbench selections and actions
  app/actions/workbench.ts
  app/components/workbench/Workbench.tsx
  app/selections.ts
  app/selections/workbench.ts
Labels: feat

#503 refactor(Workbench): turn dataset components into containers!
  app/actions/api.ts
  app/actions/workbench.ts
  app/components/DatasetList.tsx
  app/components/Structure.tsx
  app/components/chrome/CalloutBlock.tsx
  app/components/chrome/DropZone.tsx
  app/components/chrome/SidebarActionButton.tsx
  app/components/collection/Collection.tsx
  app/components/collection/CollectionHome.tsx
  app/components/compare/Compare.tsx
  app/components/compare/CompareSidebar.tsx
  app/components/compare/TableDiffSchemaHead.tsx
  app/components/dataset/PreviewNotFound.tsx
  app/components/dataset/ReadmeSegment.tsx
  app/components/dataset/StructureSegment.tsx
  app/components/form/ButtonInput.tsx
  app/components/network/LogList.tsx
  app/components/network/NetworkHome.tsx
  app/components/network/NetworkSidebar.tsx
  app/components/structure/FormatConfigEditor.tsx
  app/components/workbench/Body.tsx
  app/components/workbench/Commit.tsx
  app/components/workbench/CommitDetails.tsx
  app/components/workbench/CommitEditor.tsx
  app/components/workbench/CommitHistory.tsx
  app/components/workbench/DatasetComponent.tsx
  app/components/workbench/Metadata.tsx
  app/components/workbench/MetadataEditor.tsx
  app/components/workbench/Readme.tsx
  app/components/workbench/ReadmeEditor.tsx
  app/components/workbench/StructureEditor.tsx
  app/components/workbench/Transform.tsx
  app/components/workbench/Workbench.tsx
  app/containers/WorkbenchContainer.tsx
  app/models/dataset.ts
  app/models/store.ts
  app/routes.tsx
  app/selections.ts
  app/selections/workbench.ts
Labels: fix, refactor
