Repository qri-io/desktop, pull requests merged in 2020-09, with the labels that each got.

#588 refactor(api): adjust `fetchDataset` to use the `/get/` endpoint
  app/actions/api.ts
  app/package.json
  test/e2e/e2e.spec.ts
  version.js
Labels: api, backend, refactor

#590 chore(release): release version 0.4.5
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore

#598 fix(*): Fix various bugs
  app/components/form/DynamicEditField.tsx
  app/components/network/LogList.tsx
  app/components/workbench/components/CommitEditor.tsx
  app/components/workbench/components/MetadataEditor.tsx
  app/components/workbench/headerButtons/PublishButton.tsx
  app/components/workbench/layouts/WorkbenchSidebar.tsx
  app/main.development.js
  app/package.json
  app/scss/0.4.0/dataset.scss
  app/scss/0.4.0/network.scss
  app/scss/_dataset.scss
  app/scss/commit.scss
  app/utils/formValidation.ts
  package.json
  test/app/utils/formValidation.test.ts
  version.js
  yarn.lock
Labels: fix

#600 overhaul app navigation
  app/components/App.tsx
  app/components/DetailsBar.tsx
  app/components/Layout.tsx
  app/components/collection/Collection.tsx
  app/components/collection/ComponentList.tsx
  app/components/collection/ComponentRouter.tsx
  app/components/collection/Dataset.tsx
  app/components/collection/DatasetHeader.tsx
  app/components/collection/DisabledComponentList.tsx
  app/components/collection/EditDataset.tsx
  app/components/collection/LogList.tsx
  app/components/collection/NotInNamespace.tsx
  app/components/collection/ParseError.tsx
  app/components/collection/WorkingComponentList.tsx
  app/components/collection/collectionHome/CollectionHome.tsx
  app/components/collection/collectionHome/CollectionHomeMainContent.tsx
  app/components/collection/collectionHome/DatasetList.tsx
  app/components/collection/datasetComponents/Body.tsx
  app/components/collection/datasetComponents/Commit.tsx
  app/components/collection/datasetComponents/CommitEditor.tsx
  app/components/collection/datasetComponents/Metadata.tsx
  app/components/collection/datasetComponents/MetadataEditor.tsx
  app/components/collection/datasetComponents/Readme.tsx
  app/components/collection/datasetComponents/ReadmeEditor.tsx
  app/components/collection/datasetComponents/StructureEditor.tsx
  app/components/collection/datasetComponents/Transform.tsx
  app/components/collection/headerButtons/LinkButton.tsx
  app/components/collection/headerButtons/PublishButton.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/collection/layouts/DatasetMainContent.tsx
  app/components/collection/layouts/DatasetSidebar.tsx
  app/components/dataset/ReadmeSegment.tsx
  app/components/nav/NavSidebar.tsx
  app/components/nav/NavTopbar.tsx
  app/components/network/Network.tsx
  app/components/network/NetworkLogList.tsx
  app/components/workbench/NoDatasets.tsx
  app/components/workbench/NoDatasetsMainContent.tsx
  app/components/workbench/Workbench.tsx
  app/paths.ts
  app/reducers/log.ts
  app/routes.tsx
  app/selections.ts
  package.json
  test/e2e/e2e.spec.ts
  test/utils/e2eTestUtils.ts
  webpack.config.development.js
  webpack.config.production.js
  yarn.lock
Labels: UX, refactor

#610 feat(Remove dataset): add warning for when a user removes own dataset
  app/components/Layout.tsx
  app/components/modals/RemoveDataset.tsx
Labels: UX

#611 Update "Save Path" Checkout modal copy
  app/components/modals/LinkDataset.tsx
  test/e2e/e2e.spec.ts
Labels: UX

#612 feat(`HeadLogListItem`): add history track to sidebar
  app/components/collection/EditDataset.tsx
  app/components/collection/LogList.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/collection/layouts/DatasetSidebar.tsx
  app/components/item/HeadLogListItem.tsx
  app/components/item/LogListItem.tsx
  app/components/nav/NavTopbar.tsx
  app/reducers/dataset.ts
  app/scss/0.4.0/network.scss
  app/scss/_dataset.scss
  app/scss/_variables.scss
  app/scss/commit.scss
  stories/11-LogList.stories.tsx
  stories/4-Navbar.stories.tsx
Labels: UX, feat, refactor

#609 feat: overhaul collection view
  app/components/Layout.tsx
  app/components/chrome/BackArrow.tsx
  app/components/chrome/ForwardArrow.tsx
  app/components/chrome/HeaderColumnButton.tsx
  app/components/collection-v2/DatasetStatus.tsx
  app/components/collection/collectionHome/CollectionHome.tsx
  app/components/collection/collectionHome/DatasetCollection.tsx
  app/components/collection/collectionHome/DatasetList.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/nav/NavTopbar.tsx
  app/components/notifications/ImportProgress.tsx
  app/components/platformSpecific/DatasetStatus.electron.tsx
  app/main.development.js
  app/scss/_buttons.scss
  app/scss/_dataset-list.scss
  app/scss/_header.scss
  app/scss/_navbar.scss
  app/scss/_sidebar-layout.scss
  app/scss/style.scss
Labels: UX, collection, feat
