Repository qri-io/desktop, pull requests merged in 2020-07, with the labels that each got.

#565 fix(Storybook): get all Storybook stories to render
  DEVELOPER.md
  app/components/compare/DiffStat.tsx
  app/components/compare/LineDiff.tsx
  app/components/compare/TableDiff.tsx
  app/components/modals/SearchModal.tsx
  app/components/nav/Navbar.tsx
  app/components/network/NetworkHome.tsx
  stories/10-Dataset.stories.tsx
  stories/4-Navbar.stories.tsx
  stories/6-TableDiff.stories.tsx
  stories/Modals.stories.tsx
  stories/Network.stories.tsx
Labels: fix

#571 feat(migration): adjust `BackendProcess`, `main.dev.js` & `App.ts` so we can coordinate migrations!
  app/actions/ui.ts
  app/backend.js
  app/components/App.tsx
  app/main.development.js
  app/models/store.ts
  app/reducers/ui.ts
  app/selections.ts
Labels: feat

#574 fix(circleci): Use go1.14 to build temp_registry_server
  .circleci/config.yml
Labels: chore, fix

#573 fix(export): Use get?format=zip instead of export
  app/components/modals/ExportVersion.tsx
  app/components/workbench/WorkbenchLogList.tsx
  app/main.development.js
  app/models/modals.ts
Labels: api, fix

#572 refactor(*): changes to get desktop to work with qri v0.9.9/v0.9.10 changes
  .circleci/config.yml
  app/actions/api.ts
  app/backend.js
  app/components/App.tsx
  app/components/collection/CollectionHome.tsx
  app/components/modals/Modals.tsx
  app/components/modals/PullDataset.tsx
  app/components/network/LogList.tsx
  app/components/network/Network.tsx
  app/components/workbench/NoDatasetsMainContent.tsx
  app/main.development.js
  app/models/modals.ts
  app/models/store.ts
  app/selections.ts
  app/store/wsMiddleware.ts
  test/e2e/e2e.spec.ts
  test/utils/testQriBackend.ts
Labels: refactor

#579 fix(IncompatibleBackend): need to point `backendVer` variable to `version.js` constant
  app/components/IncompatibleBackend.tsx
  package.json
  version.js
  yarn.lock
Labels: fix

#580 chore(release): release version 0.4.3
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore
