Repository qri-io/desktop, pull requests merged in 2020-10, with the labels that each got.

#624 feat(transfers): track transfer events
  app/actions/transfers.ts
  app/components/notifications/ImportProgress.tsx
  app/models/store.ts
  app/reducers/index.ts
  app/reducers/transfers.ts
  app/store/wsMiddleware.ts
  test/app/reducers/transfers.test.ts
Labels: api, state tree

#620 fix(*): clean up `discardChanges`, double-fetching bugs, and the "uncommited changes" prompt
  app/actions/api.ts
  app/actions/workbench.ts
  app/components/collection/Collection.tsx
  app/components/collection/UncommittedChangesPrompt.tsx
  app/components/collection/WorkingComponentList.tsx
  app/components/collection/collectionHome/CollectionHome.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/collection/layouts/DatasetMainContent.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/modals/Modal.tsx
  app/models/qriRef.ts
  app/models/store.ts
  app/reducers/dataset.ts
  app/reducers/workbenchRoutes.ts
  app/reducers/workingDataset.ts
  app/selections.ts
Labels: fix, refactor

#628 fix(dataset): add back publish & show files buttons
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/nav/NavTopbar.tsx
Labels: fix, ui

#625 transfers UI
  app/components/CommitDetails.tsx
  app/components/Toast.tsx
  app/components/Transfers.tsx
  app/components/chrome/Icon.tsx
  app/components/chrome/ProgressBar.tsx
  app/components/collection/Dataset.tsx
  app/components/collection/collectionHome/DatasetList.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/collection/layouts/DatasetMainContent.tsx
  app/components/form/CheckboxInput.tsx
  app/components/form/RadioInput.tsx
  app/components/form/TristateCheckboxInput.tsx
  app/components/modals/ExportDataset.tsx
  app/components/nav/NavTopbar.tsx
  app/components/network/NetworkHome.tsx
  app/reducers/transfers.ts
  app/scss/_chrome.scss
  app/scss/_transfers.scss
  app/scss/_welcome.scss
  app/scss/style.scss
  app/store/wsMiddleware.ts
  stories/Transfers.stories.tsx
  stories/data/remoteEvents.json
Labels: feat, ui

#630 test(e2e): get e2e tests to pass with refactorings
  app/components/collection/LogList.tsx
  app/components/collection/collectionHome/CollectionHome.tsx
  app/components/collection/layouts/DatasetSidebar.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/item/WorkingLogListItem.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/Modals.tsx
  app/components/network/NetworkSidebar.tsx
  app/models/modals.ts
  app/scss/_dataset.scss
  test/e2e/e2e.spec.ts
  test/e2e/e2e_test_flows.md
  test/utils/e2eTestUtils.ts
Labels: refactor, test

#632 feat(collection home): support bulk pulling
  app/actions/api.ts
  app/components/collection/collectionHome/DatasetList.tsx
  app/models/qriRef.ts
  app/models/store.ts
Labels: actions, feat

#633 Responsive & Sortable Collection Table
  app/components/App.tsx
  app/components/Layout.tsx
  app/components/chrome/Breadcrumb.tsx
  app/components/chrome/Hamburger.tsx
  app/components/chrome/Icon.tsx
  app/components/collection/collectionHome/DatasetList.tsx
  app/components/collection/collectionHome/DatasetsTable.tsx
  app/components/collection/collectionHome/StatusIcons.tsx
  app/components/collection/collectionHome/TableRowHamburger.tsx
  app/components/collection/headerButtons/PublishButton.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/nav/NavTopbar.tsx
  app/models/modals.ts
  app/scss/0.4.0/network.scss
  app/scss/0.4.0/overlay.scss
  app/scss/_buttons.scss
  app/scss/_dataset-list.scss
  app/scss/_dataset.scss
  app/scss/_navbar.scss
  app/scss/_site.scss
  app/selections.ts
  package.json
  test/e2e/e2e.spec.ts
  test/e2e/e2e_test_flows.md
  yarn.lock
Labels: collection, feat

#638 fix(pull): adjust flow after a dataset is pulled
  app/actions/api.ts
  app/actions/selections.ts
  app/components/collection/Collection.tsx
  app/components/collection/Dataset.tsx
  app/components/collection/EditDataset.tsx
  app/components/collection/NotInNamespace.tsx
  app/components/network/Network.tsx
  app/reducers/selections.ts
  app/reducers/ui.ts
  app/selections.ts
  test/app/reducers/selections.test.ts
  test/e2e/e2e.spec.ts
  yarn.lock
Labels: fix

#640 fix(body): relax stipulations for fetching next page
  app/components/BodyTable.tsx
Labels: fix

#643 feat(export): wire up export modal with csv & zip options
  app/actions/platformSpecific/export.electron.ts
  app/actions/platformSpecific/export.web.ts
  app/components/CommitDetails.tsx
  app/components/collection/DatasetHeader.tsx
  app/components/collection/LogList.tsx
  app/components/collection/collectionHome/TableRowHamburger.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/form/ComponentAndFormatPicker.tsx
  app/components/modals/ExportDataset.tsx
  app/components/modals/RemoveDataset.tsx
  app/main.development.js
  app/models/modals.ts
  app/scss/0.4.0/dataset.scss
  app/scss/_form.scss
  app/scss/_modal.scss
  stories/Network.stories.tsx
  test/e2e/e2e.spec.ts
  test/e2e/e2e_test_flows.md
Labels: actions, feat

#646 fix: numerous tweaks & tuning
  app/components/collection/datasetComponents/CommitEditor.tsx
  app/components/modals/ExportDataset.tsx
  app/components/modals/Modal.tsx
  app/components/modals/ModalHeader.tsx
  app/components/modals/NewDataset.tsx
  app/components/modals/PullDataset.tsx
  app/components/nav/NavSidebar.tsx
  app/scss/_modal.scss
  app/scss/_navbar.scss
  app/scss/_transfers.scss
Labels: fix, ui

#649 feat(Transfers): persist transfers after completion
  app/actions/transfers.ts
  app/components/Transfers.tsx
  app/models/store.ts
  app/reducers/transfers.ts
  app/scss/_transfers.scss
  app/store/wsMiddleware.ts
  stories/11-LogList.stories.tsx
  stories/Modals.stories.tsx
  stories/data/remoteEvents.json
  test/app/reducers/transfers.test.ts
Labels: feat, ui

#645 feat(RenameDataset): add `RenameDataset` modal and rename dataset button to dataset page
  app/components/DatasetReference.tsx
  app/components/collection/Collection.tsx
  app/components/collection/collectionHome/DatasetList.tsx
  app/components/collection/headerButtons/RenameButton.tsx
  app/components/collection/layouts/DatasetLayout.tsx
  app/components/collection/layouts/DatasetSidebar.tsx
  app/components/modals/Error.tsx
  app/components/modals/Modals.tsx
  app/components/modals/RenameDataset.tsx
  app/models/modals.ts
  app/reducers/platformSpecific/workingDataset.electron.ts
  app/reducers/platformSpecific/workingDataset.web.ts
  app/reducers/workingDataset.ts
  app/scss/_dataset.scss
  app/scss/_dialog.scss
  app/utils/formValidation.ts
  stories/10-Dataset.stories.tsx
  stories/11-LogList.stories.tsx
  stories/Modals.stories.tsx
  test/e2e/e2e.spec.ts
  test/e2e/e2e_test_flows.md
  test/utils/e2eTestUtils.ts
Labels: feat, test

#650 feat(CollectionHome): add "pull" to row hamburger menu
  app/components/collection/collectionHome/StatusIcons.tsx
  app/components/collection/collectionHome/TableRowHamburger.tsx
  app/components/network/NetworkHome.tsx
  webpack.config.development.js
Labels: collection, feat, fix

#654 fix(DatasetList): ensure overlay menu can be seen for last item
  app/scss/_dataset-list.scss
Labels: fix

#655 test(e2e): adjust `atDataset`
  test/utils/e2eTestUtils.ts
Labels: test

#656 chore(release): release version 0.5.0
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore

#664 chore(version): version bump to 0.5.1-dev
  app/package.json
  package.json
  version.js
Labels: chore
