Repository qri-io/desktop, pull requests merged in 2020-02, with the labels that each got.

#425 fix(Dataset): add `Hamburger` to dataset actions
  RELEASE_PROCESS.md
  app/components/Dataset.tsx
  app/scss/_sidebar-layout.scss
Labels: fix

#426 chore(update): add logging to autoUpdate
  app/main.development.js
  package.json
  yarn.lock
Labels: chore

#427 chore(release): version bump to 0.3.4
  CHANGELOG.md
  app/package.json
  package.json
  version.js
  webpack.config.development.js
  webpack.config.production.js
  yarn.lock
Labels: chore

#429 chore(release): version bump to 0.3.5
  CHANGELOG.md
  app/package.json
  package.json
  version.js
  yarn.lock
Labels: chore

#430 feat(search): add search modal and search to navbar
  app/components/App.tsx
  app/components/ReadmeHistory.tsx
  app/components/chrome/Close.tsx
  app/components/chrome/SearchBox.tsx
  app/components/item/Dataset.tsx
  app/components/modals/Modal.tsx
  app/components/modals/SearchModal.tsx
  app/components/nav/Navbar.tsx
  app/components/network/Network.tsx
  app/constants.js
  app/containers/NavbarContainer.tsx
  app/models/modals.ts
  app/scss/0.4.0/chrome.scss
  app/scss/0.4.0/item.scss
  app/scss/0.4.0/network.scss
  app/scss/_dialog.scss
  stories/10-Dataset.stories.tsx
  stories/8-Item.stories.tsx
  stories/Modals.stories.tsx
Labels: feat

#428 refactor(routes): refactor top-level routes
  .circleci/config.yml
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/actions/selections.ts
  app/actions/workbench.ts
  app/api/.gitkeep
  app/components/App.tsx
  app/components/AppError.tsx
  app/components/AppLoading.tsx
  app/components/Code.tsx
  app/components/Collection.tsx
  app/components/DatasetComponent.tsx
  app/components/DatasetList.tsx
  app/components/IPC.tsx
  app/components/Navbar.tsx
  app/components/NoDatasets.tsx
  app/components/Signin.tsx
  app/components/Transform.tsx
  app/components/chrome/SpinnerWithIcon.tsx
  app/components/item/DetailedDatasetRefItem.tsx
  app/components/network/Network.tsx
  app/components/onboard/Signup.tsx
  app/components/onboard/Welcome.tsx
  app/components/onboard/WelcomeTemplate.tsx
  app/components/workbench/NoDatasetSelected.tsx
  app/components/workbench/UnlinkedDataset.tsx
  app/components/workbench/Workbench.tsx
  app/components/workbench/WorkbenchSidebar.tsx
  app/constants.js
  app/containers/AppContainer.tsx
  app/containers/NetworkContainer.tsx
  app/containers/WorkbenchContainer.tsx
  app/main.development.js
  app/models/dataset.ts
  app/models/store.ts
  app/routes.tsx
  app/store/api.ts
  test/e2e/e2e.spec.ts
  test/utils/e2eTestUtils.ts
  test/utils/testQriBackend.ts
  test/utils/testTempRegistry.ts
  version.js
Labels: navigation, refactor

#431 refactor(Layout): rename `SidebarLayout` to `Layout` & add `NavbarContainer`
  app/components/Collection.tsx
  app/components/CommitDetails.tsx
  app/components/Layout.tsx
  app/components/chrome/Breadcrumb.tsx
  app/components/nav/Navbar.tsx
  app/components/network/Network.tsx
  app/components/workbench/Workbench.tsx
  app/scss/0.4.0/network.scss
Labels: refactor

#432 feat (network preview & home)
  app/components/chrome/ActionButton.tsx
  app/components/chrome/ActionButtonBar.tsx
  app/components/chrome/Hamburger.tsx
  app/components/dataset/CommitPreview.tsx
  app/components/dataset/Dataset.tsx
  app/components/dataset/Overview.tsx
  app/components/dataset/Preview.tsx
  app/components/dataset/TitleBar.tsx
  app/components/modals/SearchModal.tsx
  app/components/network/Network.tsx
  app/components/network/NetworkHome.tsx
  app/components/overlay/HamburgerOverlay.tsx
  app/containers/NetworkContainer.tsx
  app/models/dataset.ts
  app/routes.tsx
  app/scss/0.4.0/network.scss
  app/store/api.ts
Labels: feat

#433 chore(dependencies): upgrade many dependencies, relax updated linting rules
  .eslintrc
  package.json
  yarn.lock
Labels: chore

#434 feat(QriRef): rename DetailedDatasetRef to VersionInfo, introduce QriRef
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/components/DatasetList.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/network/Network.tsx
  app/components/network/NetworkHome.tsx
  app/containers/NetworkContainer.tsx
  app/models/qriRef.ts
  app/models/store.ts
  app/routes.tsx
  tsconfig.dev.json
  tsconfig.json
  version.js
Labels: feat, refactor

#435 refactor(Search & Network): link the search results to routes
  app/actions/mappingFuncs.ts
  app/components/App.tsx
  app/components/dataset/DatasetDetailsSubtext.tsx
  app/components/item/DatasetItem.tsx
  app/components/item/VersionInfoItem.tsx
  app/components/modals/SearchModal.tsx
  app/components/network/Network.tsx
  app/components/network/NetworkHome.tsx
  app/models/store.ts
  stories/8-Item.stories.tsx
Labels: refactor

#452 feat(websockets): remove polling and add middleware for websockets
  app/actions/api.ts
  app/actions/session.ts
  app/components/workbench/Workbench.tsx
  app/constants.js
  app/store/configureStore.development.ts
  app/store/configureStore.production.ts
  app/store/wsMiddleware.ts
  test/e2e/e2e.spec.ts
  test/utils/e2eTestUtils.ts
Labels: feat

#458 feat(Workbench): edit in the app without checking out
  app/actions/api.ts
  app/actions/mappingFuncs.ts
  app/actions/mutations.ts
  app/components/App.tsx
  app/components/Body.tsx
  app/components/Commit.tsx
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/ContextMenuArea.tsx
  app/components/DatasetComponent.tsx
  app/components/FormatConfigFSI.tsx
  app/components/HistoryComponentList.tsx
  app/components/MetadataEditor.tsx
  app/components/Readme.tsx
  app/components/ReadmeHistory.tsx
  app/components/Structure.tsx
  app/components/chrome/StatusDot.tsx
  app/components/form/DebouncedTextInput.tsx
  app/components/form/DropdownInput.tsx
  app/components/form/DynamicEditField.tsx
  app/components/form/MultiStructuredInput.tsx
  app/components/form/MultiStructuredInputRow.tsx
  app/components/form/MultiTextInput.tsx
  app/components/form/SelectInput.tsx
  app/components/form/TextAreaInput.tsx
  app/components/form/TextInput.tsx
  app/components/item/ComponentItem.tsx
  app/components/item/SchemaItem.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/ExportVersion.tsx
  app/components/modals/LinkDataset.tsx
  app/components/structure/Schema.tsx
  app/components/workbench/Workbench.tsx
  app/components/workbench/WorkbenchSidebar.tsx
  app/containers/ReadmeContainer.tsx
  app/containers/WorkbenchContainer.tsx
  app/models/dataset.ts
  app/models/modals.ts
  app/models/store.ts
  app/package.json
  app/reducers/mutations.ts
  app/reducers/workingDataset.ts
  app/scss/_dialog.scss
  app/scss/_forms.scss
  app/scss/_modal.scss
  app/scss/_type.scss
  app/utils/datasetConvertStringToScriptBytes.ts
  app/utils/formValidation.ts
  package.json
  test/e2e/e2e.spec.ts
  version.js
  yarn.lock
Labels: feat, refactor

#464 Drag to import body updates
  app/actions/mutations.ts
  app/actions/workbench.ts
  app/components/App.tsx
  app/components/Collection.tsx
  app/components/DatasetComponent.tsx
  app/components/chrome/CalloutBlock.tsx
  app/components/chrome/DropZone.tsx
  app/components/collection/Collection.tsx
  app/components/collection/CollectionHome.tsx
  app/components/item/DatasetItem.tsx
  app/components/workbench/Workbench.tsx
  app/containers/AppContainer.tsx
  app/containers/CollectionContainer.tsx
  app/containers/WorkbenchContainer.tsx
  app/models/dataset.ts
  app/reducers/mutations.ts
  app/scss/0.4.0/chrome.scss
  app/scss/_sidebar-layout.scss
Labels: feat
