Repository qri-io/desktop, pull requests merged in 2020-01, with the labels that each got.

#380 test(e2e): expand and refine e2e tests
  .circleci/config.yml
  app/actions/api.ts
  app/actions/ui.ts
  app/components/App.tsx
  app/components/Collection.tsx
  app/components/Commit.tsx
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetList.tsx
  app/components/DatasetReference.tsx
  app/components/DatasetSidebar.tsx
  app/components/ExternalLink.tsx
  app/components/Navbar.tsx
  app/components/Readme.tsx
  app/components/Signup.tsx
  app/components/Toast.tsx
  app/components/Welcome.tsx
  app/components/chrome/Toast.tsx
  app/components/modals/CreateDataset.tsx
  app/components/modals/LinkDataset.tsx
  app/components/modals/RemoveDataset.tsx
  app/models/store.ts
  app/reducers/ui.ts
  app/routes.tsx
  app/scss/commit.scss
  app/store/configureStore.production.ts
  package.json
  test/e2e/e2e.spec.ts
  test/utils/e2eTestUtils.ts
  yarn.lock
Labels: test

#378 feat(logging): Log to a file, menu item to export it
  app/backend.js
  app/components/App.tsx
  app/main.development.js
Labels: backend, feat

#389 feat(icon): `Icon` component
  app/components/chrome/Icon.tsx
  app/scss/4.0/icons.scss
  app/scss/style.scss
  stories/2-Icons.stories.tsx
Labels: feat

#391 test(win-e2e): Tweaks to get end-to-end tests running on Windows
  .gitignore
  app/components/chrome/Icon.tsx
  package.json
  test/e2e/e2e.spec.ts
  test/log/.gitkeep
  test/utils/testQriBackend.ts
Labels: fix, test

#390 feat(TypePicker): create TypePicker and other needed components
  app/components/chrome/Icon.tsx
  app/components/item/DataType.tsx
  app/components/nav/TabPicker.tsx
  app/components/overlay/Overlay.tsx
  app/components/overlay/TypePickerOverlay.tsx
  app/components/structure/ColumnType.tsx
  app/components/structure/TypePicker.tsx
  app/scss/0.4.0/chrome.scss
  app/scss/0.4.0/icons.scss
  app/scss/0.4.0/item.scss
  app/scss/0.4.0/nav.scss
  app/scss/0.4.0/overlay.scss
  app/scss/0.4.0/structure.scss
  app/scss/0.4.0/type.scss
  app/scss/style.scss
  stories/2-Icons.stories.tsx
  stories/3-Structure.stories.tsx
Labels: feat

#388 test(e2e): round out e2e with more flows, regardless of if they pass
  app/components/DatasetList.tsx
  app/components/DatasetReference.tsx
  app/components/Metadata.tsx
  app/components/modals/LinkDataset.tsx
  test/e2e/e2e.spec.ts
Labels: test

#392 feat(Schema): create a schema editor
  app/components/Schema.tsx
  app/components/Structure.tsx
  app/components/chrome/Icon.tsx
  app/components/form/DynamicEditField.tsx
  app/components/item/SchemaItem.tsx
  app/components/overlay/Overlay.tsx
  app/components/structure/ColumnType.tsx
  app/components/structure/Schema.tsx
  app/components/structure/TypePicker.tsx
  app/scss/0.4.0/form.scss
  app/scss/0.4.0/item.scss
  app/scss/0.4.0/structure.scss
  app/scss/_dataset.scss
  app/scss/style.scss
  stories/3-Structure.stories.tsx
  stories/5-form.stories.tsx
Labels: feat

#394 fix(commit, MetadataEditor): fix meta editing and the flow after you commit
  RELEASE_PROCESS.md
  app/actions/api.ts
  app/actions/mutations.ts
  app/components/Body.tsx
  app/components/Commit.tsx
  app/components/DatasetList.tsx
  app/components/MetadataEditor.tsx
  app/components/modals/LinkDataset.tsx
  app/containers/BodyContainer.tsx
  app/containers/CommitContainer.tsx
  app/containers/CommitDetailsContainer.tsx
  app/reducers/mutations.ts
  app/reducers/selections.ts
  app/reducers/ui.ts
  app/reducers/workingDataset.ts
  test/e2e/e2e.spec.ts
  test/utils/e2eTestUtils.ts
Labels: fix

#343 initial line & table diff components
  app/components/compare/LineDiff.tsx
  app/components/compare/TableDiff.tsx
  app/scss/_lineDiff.scss
  app/scss/_tableDiff.scss
  app/scss/style.scss
  stories/2-LineDiff.stories.tsx
  stories/3-TableDiff.stories.tsx
Labels: ui

#402 refactor(Dataset): move fetching into Dataset and remove Containers
  app/actions/api.ts
  app/actions/selections.ts
  app/actions/session.ts
  app/components/App.tsx
  app/components/CommitDetails.tsx
  app/components/Dataset.tsx
  app/components/DatasetReference.tsx
  app/components/DatasetSidebar.tsx
  app/components/HistoryComponentList.tsx
  app/containers/CommitDetailsContainer.tsx
  app/containers/DatasetContainer.tsx
  app/containers/DatasetSidebarContainer.tsx
  app/containers/MetadataEditorContainer.tsx
  app/containers/ReadmeContainer.tsx
  app/containers/StructureContainer.tsx
  app/containers/TransformContainer.tsx
  app/models/store.ts
  app/reducers/commitDetail.ts
  app/reducers/selections.ts
  app/scss/_dataset.scss
  test/e2e/e2e.spec.ts
Labels: fix

#401 feat(log): Set the --log-all flag when starting our own backend
  app/backend.js
Labels: backend, feat

#403 feat(main process logging): add logging for main process
  app/backend.js
  app/main.development.js
  package.json
  yarn.lock
Labels: fix, main process

#404 chore(release): version bump v0.3.2
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore

#405 fix(body): refine props to Body components, fix fetching status
  RELEASE_PROCESS.md
  app/actions/api.ts
  app/components/Body.tsx
  app/components/BodyTable.tsx
  app/components/CommitDetails.tsx
  app/components/ComponentList.tsx
  app/components/Dataset.tsx
  app/components/DatasetComponent.tsx
  app/components/chrome/Icon.tsx
  app/containers/BodyContainer.tsx
  app/containers/DatasetContainer.tsx
  app/models/details.ts
  app/models/store.ts
  app/reducers/commitDetail.ts
  app/scss/_body.scss
Labels: fix

#420 chore(release): version bump to 0.3.3
  CHANGELOG.md
  app/package.json
  package.json
  version.js
Labels: chore
